version: '3.4'

services:
  catalogdb:
    image: mongo
  discountdb:
   image: postgres


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/Discount/Discount.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:

